using TruckVisit.Domain.Visits;

namespace TruckVisit.Application.Visits;

/// <summary>
/// Projects the aggregate onto the wire contracts.
/// </summary>
/// <remarks>
/// Written by hand rather than generated by a mapping library. At this size the explicit version is
/// shorter than the configuration a convention-based mapper would need, and — more importantly — a
/// renamed property becomes a compile error here instead of a field that quietly turns null in
/// production (ADR-009).
/// </remarks>
public static class VisitMapper
{
    public static VisitDetailView ToDetail(Visit visit)
    {
        ArgumentNullException.ThrowIfNull(visit);

        return new VisitDetailView(
            visit.Id,
            visit.TerminalId.Value,
            visit.CurrentStatus.ToString(),
            new TruckView(visit.Truck.UnitNumber.Value, visit.Truck.LicensePlate.Value),
            new DriverView(visit.Driver.FullName, visit.Driver.DocumentId, visit.Driver.PhoneNumber),
            [.. visit.Movements.Select(ToView)],
            [.. visit.StatusHistory.OrderBy(entry => entry.Sequence).Select(ToView)],
            visit.CreatedTime,
            visit.CreatedBy);
    }

    private static MovementView ToView(Movement movement) => new(
        movement.Id,
        movement.Type.ToString(),
        movement.UnitNumber.Value,
        movement.From.Value,
        movement.To.Value);

    private static StatusChangeView ToView(StatusChange change) => new(
        change.Sequence,
        change.From?.ToString(),
        change.To.ToString(),
        change.ChangedAt,
        change.ChangedBy,
        change.Reason);
}
