// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TruckVisit.Infrastructure.Persistence;

#nullable disable

namespace TruckVisit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TruckVisitDbContext))]
    [Migration("20260921173049_MovementCompletionAndAuditChain")]
    partial class MovementCompletionAndAuditChain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TruckVisit.Domain.Visits.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("LastStatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_visits_created_by");

                    b.HasIndex("TerminalId", "CreatedTime")
                        .HasDatabaseName("ix_visits_terminal_created");

                    b.HasIndex("TerminalId", "CurrentStatus", "CreatedTime")
                        .HasDatabaseName("ix_visits_terminal_status_created");

                    b.ToTable("visits", (string)null);
                });

            modelBuilder.Entity("TruckVisit.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid");

                    b.HasKey("Key", "UserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_created_at");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("TruckVisit.Domain.Visits.Visit", b =>
                {
                    b.OwnsOne("TruckVisit.Domain.Visits.Driver", "Driver", b1 =>
                        {
                            b1.Property<Guid>("VisitId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CompanyName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("driver_company_name");

                            b1.Property<string>("DocumentId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("driver_document_id");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("driver_full_name");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("driver_phone_number");

                            b1.HasKey("VisitId");

                            b1.HasIndex("CompanyName");

                            b1.ToTable("visits");

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.OwnsMany("TruckVisit.Domain.Visits.Movement", "Movements", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CompletedBy")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("From")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("To")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("UnitNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid>("VisitId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("CompletedAt");

                            b1.HasIndex("From");

                            b1.HasIndex("To");

                            b1.HasIndex("UnitNumber");

                            b1.HasIndex("VisitId");

                            b1.ToTable("visit_movements", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.OwnsMany("TruckVisit.Domain.Visits.StatusChange", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("ChangedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ChangedBy")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("EntryHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .IsFixedLength();

                            b1.Property<string>("From")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("PreviousHash")
                                .HasMaxLength(64)
                                .HasColumnType("character(64)")
                                .IsFixedLength();

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer");

                            b1.Property<string>("To")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("VisitId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VisitId", "Sequence")
                                .IsUnique();

                            b1.ToTable("visit_status_history", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.OwnsOne("TruckVisit.Domain.Visits.Truck", "Truck", b1 =>
                        {
                            b1.Property<Guid>("VisitId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LicensePlate")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("truck_license_plate");

                            b1.Property<string>("UnitNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("truck_unit_number");

                            b1.HasKey("VisitId");

                            b1.HasIndex("LicensePlate");

                            b1.ToTable("visits");

                            b1.WithOwner()
                                .HasForeignKey("VisitId");
                        });

                    b.Navigation("Driver")
                        .IsRequired();

                    b.Navigation("Movements");

                    b.Navigation("StatusHistory");

                    b.Navigation("Truck")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
